// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.0;

bytes32 constant WORKLOAD_VERIFIER_PROXY_SALT = keccak256(bytes("WORKLOAD_VERIFIER_PROXY_SALT"));
bytes32 constant WORKLOAD_VERIFIER_IMPL_SALT = keccak256(bytes("WORKLOAD_VERIFIER_IMPL_SALT"));
bytes32 constant CERT_CHAIN_REGISTRY_PROXY_SALT = keccak256(bytes("CERT_CHAIN_REGISTRY_PROXY_SALT"));
bytes32 constant CERT_CHAIN_REGISTRY_IMPL_SALT = keccak256(bytes("CERT_CHAIN_REGISTRY_IMPL_SALT"));
