[package]
name = "automata-tee-workload-measurement"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Automata TEE workload measurement and attestation utilities"
repository = "https://github.com/automata-network/automata-tee-workload-measurement"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
tracing.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
hex.workspace = true
