// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {TEEType, CloudType, TeeReportType, Measurement} from "../lib/LibTEE.sol";
import {WorkloadCollaterals} from "./IWorkloadVerifier.sol";
import {CertPubkey, SignatureAlgorithm} from "@automata-network/automata-tpm-attestation/lib/LibX509.sol";

struct CVMIdentity {
    bytes tpmtPublic;
    SignatureAlgorithm sigAlgo;
}

struct CVMConfig {
    TEEType teeType;
    CloudType cloudType;
    uint64 expiredAt;
    bytes32 measurementHash;
    CVMIdentity cvmIdentity;
    CertPubkey tpmAk;
    bytes teeAttestationOutput;
}

struct CVMIdentityCertification {
    bytes certInfo;
    bytes akCertificationSig;
}

interface ICVMRegistry {
    error CVM_NOT_REGISTERED();
    error CVM_IDENTITY_INVALID();
    error CVM_IDENTITY_MISMATCH(bytes32 expected, bytes32 actual);
    error CVM_IDENTITY_REVOKED(bytes32 cvmIdentityHash);
    error CVM_ALREADY_REGISTERED(bytes32 cvmIdentityHash);
    error CVM_EXPIRED();
    error INVALID_SIGNATURE();
    error UNSUPPORTED_HASH_ALGORITHM(uint16 hashAlgo);
    error INVALID_TPM_QUOTE(string err);
    error INVALID_TPM_MEASUREMENT(string err);
    error TEE_REPORT_ALREADY_USED(bytes32 teeReportHash);
    error TPM_QUOTE_ALREADY_USED(bytes32 tpmQuoteHash);
    error AK_ALREADY_BOUND(bytes32 akHash, bytes32 existingIdentity);
    error AK_BINDING_MISMATCH(bytes32 akHash, bytes32 expected, bytes32 actual);

    event CVMRegistered(bytes32 indexed cvmIdentityHash);
    event CVMRefreshed(bytes32 indexed cvmIdentityHash);
    event CVMIdentityRotated(bytes32 indexed oldHash, bytes32 indexed newHash);

    /**
     * @notice invoke this method to attest their CVM and
     * register the workload generated key as their onchain identity
     *
     * @dev must check TEE and TPM bindings
     * @dev must also check cvmIdentity key is generated by the same TPM.
     * @notice caller may optionally specifies their TTL, otherwise uses
     * DEFAULT_TEE_TTL
     *
     * @dev creates cvmConfigs[cvmIdentityHash] => cvmConfig
     */
    function registerCvm(
        CloudType cloudType,
        TEEType teeType,
        uint64 teeTTL,
        TeeReportType teeReportType,
        bytes calldata teeAttestationReport,
        CVMIdentity calldata cvmIdentity,
        CVMIdentityCertification calldata cvmCertification,
        WorkloadCollaterals calldata wc
    ) external returns (Measurement memory);

    /**
     * @notice invoke this method to resubmit the TEE report for existing
     * CVMs
     *
     * @dev must make sure that the TPM quote is signed by the same AK from
     * registration
     *
     * @dev must prevent re-using BOTH TEE and TPM reports
     *
     * @dev measurement updates occur here, but CVMIdentity rotation flow
     * must go through the rotateCvmIdentityKey() call.
     *
     * @dev updates cvmConfigs[cvmIdentityHash] => cvmConfig
     */
    function refreshCvm(
        bytes32 cvmIdentityHash,
        uint64 teeTTL,
        TeeReportType teeReportType,
        bytes calldata teeAttestationReport,
        WorkloadCollaterals calldata wc
    ) external returns (Measurement memory);

    /**
     * @notice call this method if:
     * (0) TEE report is still fresh, saves gas
     * (1) Users intend to rotate their identity keys
     *
     * @dev must check block.timestamp <= config.expiredAt
     *
     * @dev the entire config will be re-mapped using the new CVM identity hash
     * @dev cvmConfigs[updateCvmIdentityHash] => cvmConfig
     * @dev delete / unset cvmConfigs[cvmIdentityHash]
     *
     */
    function rotateCvmIdentityKey(
        bytes32 cvmIdentityHash,
        CVMIdentity calldata newCvmIdentity,
        CVMIdentityCertification calldata newCvmCertification
    ) external;

    /**
     * @notice Checks whether a registered CVM is still within its validity period
     * @param cvmIdentityHash The keccak256 hash of the CVM's public key and signature algorithm
     * @return True if block.timestamp <= expiredAt, false otherwise
     * @dev Reverts with CVM_NOT_REGISTERED if the cvmIdentityHash is not registered
     */
    function checkCvmValidity(bytes32 cvmIdentityHash) external view returns (bool);

    /**
     * @notice Checks whether a CVM identity hash has been registered
     * @param cvmIdentityHash The keccak256 hash of the CVM's public key and signature algorithm
     * @return True if the CVM is registered (cloudType != CloudType.Unset), false otherwise
     */
    function hasRegistered(bytes32 cvmIdentityHash) external view returns (bool);

    /**
     * @notice Retrieves the measurement hash for a registered CVM
     * @param cvmIdentityHash The keccak256 hash of the CVM's public key and signature algorithm
     * @return The keccak256 hash of the CVM's measurement data (PCRs, TEE report fields, etc.)
     * @dev Reverts with CVM_NOT_REGISTERED if the cvmIdentityHash is not registered
     */
    function getMeasurementHash(bytes32 cvmIdentityHash) external view returns (bytes32);

    /**
     * @notice Retrieves the CVM identity (TPM public key data) for a registered CVM
     * @param cvmIdentityHash The keccak256 hash of the CVM's public key and signature algorithm
     * @return The CVMIdentity struct containing tpmtPublic bytes and signature algorithm
     * @dev Reverts with CVM_NOT_REGISTERED if the cvmIdentityHash is not registered
     */
    function getCvmIdentity(bytes32 cvmIdentityHash) external view returns (CVMIdentity memory);

    /**
     * @notice Retrieves the full configuration for a registered CVM
     * @param cvmIdentityHash The keccak256 hash of the CVM's public key and signature algorithm
     * @return The CVMConfig struct containing TEE type, cloud type, expiration, measurements,
     *         identity, TPM attestation key, and TEE attestation output
     * @dev Reverts with CVM_NOT_REGISTERED if the cvmIdentityHash is not registered
     */
    function getCvmConfig(bytes32 cvmIdentityHash) external view returns (CVMConfig memory);
}
